FileList = [
	"config/sessions.js"
	, "config/speakers.js"
	, "helpers/application.js"
	, "ui/button_group.js"
	, "ui/sub_tabs.js"
	, "helpers/ui.js"
	, "lib/db_updater.js"
	, "lib/formatter.js"
	, "layouts/application.js"
	, "layouts/news.js"
	, "layouts/ipad/application.js"
	, "layouts/ipad/nav.js"
	, "layouts/ipad/footer.js"
	, "controllers/maps.js"
	, "controllers/sessions.js"
	, "controllers/speakers.js"
	, "controllers/news.js"
	, "views/ipad/sessions/index.js"
	, "views/ipad/speakers/index.js"
	, "views/maps/index.js"
	, "views/sessions/index.js"
	, "views/sessions/table.js"
	, "views/sessions/show.js"
	, "views/speakers/index.js"
	, "views/speakers/show.js"
	, "views/news/index.js"
]
